### PR TITLE
Added the basic code for reading and writing image

### PR DESCRIPTION
**Pull request by anmolj7**
Closes the issue #3 
I added the code so it's even easier to view bigger images on a smaller screen.
For example:
Screenshot from 2021-10-17 21-26-43
Screenshot from 2021-10-17 21-26-54

### CODE REVIEW

**Comment by anmolj7** [comment]
By writing image, do you mean saving the image?

**Comment by MohithReddy1** [comment]
Ya

**Comment by anmolj7** [comment]
okay cool! I'll add it in a while!

**Comment by MohithReddy1** [comment]
Approved

**Pull request merged**
