### PR TITLE
Added the code to rotate a particular image

### PR DESCRIPTION
**Pull request by anmolj7**
# Related Issue
Closes Issue #6 

# Screenshots
Screenshot from 2021-10-18 10-34-28

### CODE REVIEW

**Comment by anmolj7** [comment]
Is this code alright?

**Comment by MohithReddy1** [comment]
Also write code for different angles (45, 180, 270 etc..).

**Comment by anmolj7** [comment]
okay cool, wait!

**Comment by MohithReddy1** [comment]
also write readme file

**Comment by anmolj7** [comment]
Made the required changes!

**Pull request merged**
